version: "3.9"
services:
  frontend:
    build: ./frontend
    container_name: future-forge-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://api:5000
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: .
    container_name: future-forge-api
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/future_forge
      JWT_SECRET: ${JWT_SECRET:-change_me_to_a_strong_secret}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:3000,http://frontend:3000}
      RATE_LIMIT_WINDOW_MIN: ${RATE_LIMIT_WINDOW_MIN:-15}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:7
    container_name: future-forge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data: